### ISSUE TITLE
When app starts there is a notification that auth token is missing - but then the account loads OK in another moment

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/mobile#3261]
ISS-155, reported by @PeterPetrik 

When app starts there is a notification that auth token is missing - but then the account loads OK in another moment

**Comment by wonder-sk** [comment]
This can be replicated by using an old "expire" datetime stored in Input.ini

The code flow is quite complicated if this happens, causing also uneccessary extra API calls, in total:
- 2x login (instead of 1)
- 4x list projects by name (instead of 1)
- 2x user info (instead of 1)

If the token has not expired yet, it's all good, without extra API calls.

There is an ugly QEventLoop used when authenticating, which also triggers unexpected code paths. It would be good to clean this up, together with a cleanup of spaghetti of signals, to have better control of what is going on (with a well-defined state machine).

I suggest to address that after the redesign release :slightly_smiling_face:
