### ISSUE TITLE
Filter expression not working for Value Relation widget in 2024.1.0

### ISSUE THREAD

**Issue by raherin** [MerginMaps/mobile#3429]
When using a filter expression on a value relations widget, the app will add all values that meet the filter expression when only one value is selected in the drop-down menu while filling out the form. This can be reproduced in the example project [support/form_setup](https://app.merginmaps.com/projects/support/form_setup/tree). 

To reproduce the issue:

1. Have a survey layer with a Value Relation widget and set a filter expression based on the value of another field:
<img width="1100" alt="image" src="https://github.com/MerginMaps/mobile/assets/26321345/a8e9b2bc-0001-44ac-9782-209f75051bbd">

2. The expected behaviour, which is reproduced in QGIS, is that when selecting a plant type in the form, you will be able to select a plant of that type in the form. In this case, 'Vegetable' was selected as the plant type and 'Carrot' as the plant species:
<img width="536" alt="image" src="https://github.com/MerginMaps/mobile/assets/26321345/34513170-4f6b-47ad-b7b5-84edc65473a7">

3. When filling out the form in the app, all of the species are saved to the field in the form. See video below:

https://github.com/MerginMaps/mobile/assets/26321345/1acb0518-53bc-4233-900d-e86ee86c6773

**Comment by uclaros** [comment]
This weird behavior is actually caused by the project not being set up properly:

While the value relation for field type is properly set:
- Key column is `Code`, -> stores values [A, B, C ...]
- Value column is Description, -> displays values [Fruit, Vegetable, Flower ...]

The value relation for sub-type is wrong:
- filter expression is OK, only shows entries where `Code` matches the type's selected Key.
- Value column is Species, -> displays values [Carrot, apple ...]
- :x: Key column is **Class**, -> stores values **[A, B, C ...] which _do not correspond to a single Value entry_**

Setting the Key column to either _fid_ or _Species_ solves it, as there is now a 1-1 connection to the Value values.



So the question is: _what should be displayed when the selected **Key** corresponds to multiple **Value**s, and should we somehow warn users about it?_
QGIS handles it by displaying the _first matching value_.
I believe our approach is more correct, we display a concatenated string of all corresponding values.

**Comment by wonder-sk** [comment]
Note: there is a ticket for the plugin to detect such problems: https://github.com/MerginMaps/qgis-plugin/issues/317

**Comment by tomasMizera** [comment]
Ping @raherin
