### ISSUE TITLE
 After adding a new feature the canvas goes blank on iOS

### ISSUE THREAD

**Issue by alexd0793** [MerginMaps/mobile#3605]
As seen in the following video.For more info please contact @veronikahlinkova 

https://github.com/user-attachments/assets/9aaf8c45-6d93-455b-b4b0-b9c3b245a83f

**Comment by VitorVieiraZ** [comment]
Since the custom map for this project covers only one specific area/country ( around UK ), centering on your current GPS position ( with autolock GPS setting enabled ) may cause the map to appear blank if you are outside this covered region. However, if you zoom out to maximum level, you can view the covered area on map.
